version: '3.8'

services:
  app:
    container_name: Doctor-Appointments-Server
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app           
      - /usr/src/app/node_modules  
    environment:
      NODE_ENV: development
      DB_URL: ${DB_URL}           
    command: npm start        